version: '3'

services:

  wildfire-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/wildfires_project
    ports:
      - 8502:8501

    command: streamlit run app.py
      
      