version: 2.1

jobs:
  lint-app:
    docker:
      - image: python:3.10-slim
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install 
          command: |
            apt-get update 
            apt install -y make
            pip install pandas
      - run:
          name: Lint 
          command: |
            pip install pylint
            make lint
      - run:
          name: Test 
          command: |
            make test

workflows:
  default:
    jobs:
      - lint-app
            
