version: 2.1

commands:
  install_ansible:
    description: Install Ansible
    steps:
      - run:
          name: Install Ansible
          command: |
            sudo apt update
            sudo apt install software-properties-common -y
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible -y


jobs:
  python_anywhere:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - install_ansible
      - attach_workspace:
          at: ~/
      - run:
          name: Configure Server
          command: |
            ssh-keyscan -H ssh.pythonanywhere.com >> ~/.ssh/known_hosts
            cat ~/.ssh/authorized_keys
            echo "Done"
            echo "Done"
            cd .circleci/ansible
            cat inventory.txt
            ssh fiverock@ssh.pythonanywhere.com     
            # ansible-playbook -i inventory.txt main.yml --private-key ~/.ssh/authorized_keys


workflows:
  default:
    jobs:
      - python_anywhere
