version: 2.1

jobs:
  test-data:
    docker:
      - image: python:3.8.13-slim
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Installing dependenies
          command: |
            ls
            pip install -r requirements.txt

      - run:
          name: Run test
          command: pytest test.py

  build-app:
    docker:
      - image: python:3.8.13-slim
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Installing dependenies
          command: |
            ls
            pip install -r requirements.txt

      - run:
          name: Run test
          command: python app.py

workflows:
  default:
    jobs:
      - test-data
      - build-app:
          requires: [test-data]
            
