version: 2.1

jobs:
  test-app:
    docker:
      - image: python:3.10-slim
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install 
          command: |
            apt-get update
            make install
      - run:
          name: Download file
          command: make download_file
      - run:
          name: Test 
          command: make test
      - run:
          name: Lint 
          command: make lint

workflows:
  default:
    jobs:
      - test-app
            
